### ISSUE TITLE
解析 uint64 类型

### ISSUE THREAD

**Issue by zhangbenqi** [Zhang19910325/protoBufferForWeichat#2]
解析 uint64 类型 没有转化成具体的数值，而是 Long 对象类似 {low: 654, high: 0, unsigned: true} ，能在解析时直接转化为数值吗？

**Comment by Zhang19910325** [comment]
Long对象里面有一个toNumber方法，这个可以转化成具体的数字；不过js里面的用var64位标示是有问题的js最高的安全值是2的53次方，超过这个值的时候可能会丢失精度。
