### ISSUE TITLE
生成的二进制不正确，用其他语言的运行时无法正常解析

### ISSUE THREAD

**Issue by wuweiplus** [Zhang19910325/protoBufferForWeichat#3]
经过测试发现遇到嵌套消息时，序列化出的二进制数据与用protobuf.js static-module序列化的结果不一致。
encoder.js:73 应该改为
```
_types[index].encode(ref,writer.uint32((field.id << 3 | 2) >>> 0).fork()).ldelim();
```

**Comment by Zhang19910325** [comment]
感谢你的bug。嗯，你说的对，这里类型值确实有问题！之前测试的demo里面已经fix了，demo里面的weichatPb是正常的。但是代码同步没做好，不过现在这个已经修复了。

**Comment by Zhang19910325** [comment]
demo里面也有嵌套消息的测试过程'testComplexConversion'。
