### ISSUE TITLE
encode在模拟器正常，IOS手机上出问题

### ISSUE THREAD

**Issue by littleferry** [Zhang19910325/protoBufferForWeichat#5]
var buffer = msg.encode().finish();
console.log("buffer", buffer);
模拟器上输出的日志：
Uint8Array(92) [8, 1, 18, 88, 10, 14, 49, 56, 48, 46, 49, 53, 48, 46, 49, 56, 54, 46, 52, 50, 16, 168, 44, 26, 6, 104, 113, 121, 120, 109, 113, 34, 8, 49, 50, 51, 121, 120, 51, 50, 49, 42, 3, 47, 121, 120, 50, 20, 51, 95, 49, 53, 52, 49, 49, 52, 57, 49, 55, 54, 57, 51, 49, 50, 57, 55, 50, 56, 58, 20, 51, 95, 49, 53, 52, 49, 49, 52, 57, 49, 55, 54, 57, 51, 49, 50, 57, 55, 50, 56, 66, 0]
而在IOS的微信上输出：
复制不出来，我手动输入在手机看到的日志：
Object {"0": 8, "1": 1, "2": 18, "3": 88 ...
由于刚接触小程序和html5开发，是不是我犯了一个常识性错误，这种对象序列化我如何跨平台通过WSScocket传到服务器去正确解析？

**Comment by Zhang19910325** [comment]
你好，你应该是传错类型了，你这里取出的buffer是Uint8Array，而微信websocket传输要求是ArrayBuffer，所要你把你要取出这个类型数据，将你的代码换成
```js
var buffer = msg.encode().finish();
buffer = buffer.buffer;
console.log("buffer", buffer);
```
试试

**Comment by littleferry** [comment]
这样写在IOS手机上输出是：
wx.sendSocketMessage msg: 
Object {"0": 8, "1": 1, "2": 18, "3": 88 ...
wx.sendSocketMessage msg.buffer: 
Object { }

在模拟器上输出是：
wx.sendSocketMessage msg:  Uint8Array(92) [8, 1, 18, 88, 10, 14, 49, 56, 48, 46, 49, 53, 48, 46, 49, 56, 54, 46, 52, 50, 16, 168, 44, 26, 6, 104, 113, 121, 120, 109, 113, 34, 8, 49, 50, 51, 121, 120, 51, 50, 49, 42, 3, 47, 121, 120, 50, 20, 51, 95, 49, 53, 52, 49, 49, 52, 57, 49, 55, 54, 57, 51, 49, 50, 57, 55, 50, 56, 58, 20, 51, 95, 49, 53, 52, 49, 49, 52, 57, 49, 55, 54, 57, 51, 49, 50, 57, 55, 50, 56, 66, 0]
wx.sendSocketMessage msg.buffer:  ArrayBuffer {}

**Comment by Zhang19910325** [comment]
输出是这样没错，但现在这个buffer是可以用来传输的，不过一般情况下打印不出了，

**Comment by Zhang19910325** [comment]
没问题的话我将这个问题关掉了。

**Comment by littleferry** [comment]
多谢，问题解决了。
