### ISSUE TITLE
.encode().finish().buffer的长度不对

### ISSUE THREAD

**Issue by littleferry** [Zhang19910325/protoBufferForWeichat#6]
var msg = pbmsg.encode().finish();
msg.length正确，msg.buffer的长度不对，始终是8192
此问题我通过var base64 = wx.arrayBufferToBase64(msg.buffer);的方式验证过，输出的base64长度不正常，同时，我从服务器端接收的到长度是8192
麻烦帮我看看是什么问题，多谢。

**Comment by Zhang19910325** [comment]
```js
var buffer = msg.buffer.slice(msg.byteOffset, msg.byteOffset + msg.byteLength);
```
你这里是取出的buffer缓冲区对应不一致，这个是系统分配的;正确的缓冲区部分应该用上面这种方式取出，这是我的问题，当初给的解答有偏差。到时候我在这里加个方法：取正确缓冲区的方式，这样就可以用于websocket传输了。

**Comment by littleferry** [comment]
good，就是这个问题，我刚才还跟到pool.js中打日志看了，发现把8192调小一点，调到比我实际的length小，长度就对了，还是你的这个方法靠谱，由于我刚接触小程序开发，连slice方法都不知道，一直苦于msg.buffer的类型只能知道是objcet，居然不知道还有slice方法，顺便问一下，object对象如何反查其类型呢？

**Comment by Zhang19910325** [comment]
可以了解一下typeof 和 instanceof
